const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { loadScripts } = require('./helpers/inline-scripts.cjs');

// Initially run against the renderer block in e0734ec, before extraction.
const context = loadScripts(['renderer']);
vm.runInContext('Math.random = () => { throw Error("Unexpected unseeded randomness"); }', context);
const { M4, V, seeded } = vm.runInContext('({ M4, V, seeded })', context);
const identity = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
const close = (actual, expected, tolerance = 1e-6) => {
  assert.equal(actual.length, expected.length);
  Array.from(actual).forEach((value, i) => assert.ok(
    Number.isFinite(value) && Math.abs(value - expected[i]) <= tolerance,
    `component ${i}: ${value} ≈ ${expected[i]}`,
  ));
};

// Fixed unsigned outputs captured from e0734ec, not generated by this test.
const sequences = [
  [0, [1144304738, 1416247, 958946056, 627933444, 2007157716, 2340967985]],
  [1409, [3565477385, 2711512164, 3043028107, 2990900752, 800103645, 2796287591]],
  [-1, [3850105811, 813802916, 3073704848, 4054706436, 3630262831, 2315588663]],
  [2147483648, [3524353788, 1924613307, 3365584844, 2199219949, 3602660773, 1806097541]],
  [77, [1827943904, 181332479, 2989326142, 2086917005, 497196720, 3548107640]],
];
const take = (rng, count = 6) => Array.from({ length: count }, () => rng() * 4294967296);

test('seeded retains fixed sequences for zero, mission, negative and overflowing signed seeds', () => {
  for (const [seed, expected] of sequences) assert.deepEqual(take(seeded(seed)), expected);
});

test('seeded retains signed 32-bit coercion and independent generator state', () => {
  for (const seed of [4294967296, .9, NaN, Infinity, undefined, '0']) {
    assert.deepEqual(take(seeded(seed)), sequences[0][1]);
  }
  for (const seed of [4294967295, -1.9]) assert.deepEqual(take(seeded(seed)), sequences[2][1]);
  assert.deepEqual(take(seeded(4294967296 + 1409)), sequences[1][1]);
  const a = seeded(1409), b = seeded(1409);
  for (const expected of sequences[1][1]) {
    assert.equal(a() * 4294967296, expected);
    seeded(77)(); // A third instance must not consume either stream.
    assert.equal(b() * 4294967296, expected);
  }
  const rng = seeded(1409);
  for (let i = 0; i < 10000; i++) { const value = rng(); assert.ok(value >= 0 && value < 1); }
});

test('vector subtraction, dot, cross and normalization preserve inputs and zero fallback', () => {
  const a = Object.freeze([3, 4, 0]), b = Object.freeze([1, -2, 5]);
  close(V.sub(a, b), [2, 6, -5]);
  assert.equal(V.dot(a, b), -5);
  close(V.cross(a, b), [20, -15, -10]);
  assert.equal(V.dot(V.cross(a, b), a), 0);
  close(V.norm(a), [.6, .8, 0]);
  close(V.norm([0, 0, 0]), [0, 0, 0]);
  close(V.norm([1e-20, 0, 0]), [1, 0, 0]);
  assert.notStrictEqual(V.norm(a), a);
});

test('identity returns independent Float32 matrices and point keeps homogeneous coordinates', () => {
  const a = M4.identity(), b = M4.identity();
  assert.equal(Object.prototype.toString.call(a), '[object Float32Array]');
  assert.notStrictEqual(a, b);
  a[0] = 99;
  assert.deepEqual(Array.from(b), identity);
  close(M4.point(b, 2, 3, 4), [2, 3, 4, 1]);
  const translation = Object.freeze([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 20, 30, 2]);
  close(M4.point(translation, 2, 3, 4), [12, 23, 34, 2]); // No implicit perspective divide.
  close(M4.point(translation, 2, 3, 4, 0), [2, 3, 4, 0]);
});

test('column-major multiplication composes right-to-left without mutating inputs', () => {
  const translation = Object.freeze([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 20, 30, 1]);
  const scale = Object.freeze([2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1]);
  const result = M4.mul(translation, scale);
  assert.equal(Object.prototype.toString.call(result), '[object Float32Array]');
  close(result, [2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 10, 20, 30, 1]);
  close(M4.point(result, 1, 2, 3), [12, 26, 42, 1]);
  close(M4.point(M4.mul(scale, translation), 1, 2, 3), [22, 66, 132, 1]);
  close(M4.mul(result, M4.identity()), result);
  close(M4.mul(M4.identity(), result), result);
});

test('orthographic and perspective projections retain clip-space conventions', () => {
  const ortho = M4.ortho(-2, 6, -3, 5, 1, 11);
  close(M4.point(ortho, -2, -3, -1), [-1, -1, -1, 1]);
  close(M4.point(ortho, 6, 5, -11), [1, 1, 1, 1]);
  const perspective = M4.perspective(Math.PI / 2, 2, 1, 11);
  close(perspective, [.5, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1.2, -1, 0, 0, -2.2, 0]);
  const project = (x, y, z) => { const p = M4.point(perspective, x, y, z); return p.slice(0, 3).map(v => v / p[3]); };
  close(project(0, 0, -1), [0, 0, -1]);
  close(project(22, 11, -11), [1, 1, 1]);
});

test('look matrix maps the eye to origin and target onto negative camera Z', () => {
  const eye = Object.freeze([3, 4, 0]), target = Object.freeze([0, 0, 0]);
  const view = M4.look(eye, target);
  close(M4.point(view, ...eye), [0, 0, 0, 1]);
  close(M4.point(view, ...target), [0, 0, -5, 1]);
  close(M4.point(view, 0, 0, -1, 0), [1, 0, 0, 0]);
  // Current degeneracy is a zero basis, not a repaired camera orientation.
  close(M4.look([0, 0, 0], [0, 0, 0]), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]);
});

test('inverse handles row pivoting, keeps input and retains singular/near-singular identity fallback', () => {
  const matrix = Object.freeze([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 3, 4, 1]);
  const inverse = M4.inverse(matrix);
  close(M4.mul(matrix, inverse), identity);
  close(M4.mul(inverse, matrix), identity);
  close(M4.point(inverse, ...M4.point(matrix, 7, 8, 9)), [7, 8, 9, 1]);
  close(M4.inverse(new Float32Array(16)), identity);
  const tiny = M4.identity(); tiny[0] = 1e-11;
  close(M4.inverse(tiny), identity);
  tiny[0] = 1e-9;
  close(M4.mul(tiny, M4.inverse(tiny)), identity);
});
