/* GPU adapter for CPU-generated world data, plus entity models. */
'use strict';

class BattlefieldView {
  R: MeridianRenderer;
  data: WorldRenderData | null;
  world: Battlefield | null;
  fogVersion: number;
  private worldMeshes = new Set<string>();
  constructor(renderer: MeridianRenderer) {
    this.R = renderer;
    this.data = null;
    this.world = null;
    this.fogVersion = -1;
  }
  sync(world: Battlefield, fogOn = true) {
    const R = this.R, layout = world.renderData,
      { extent: EXTENT, cellSize: CELL, gridSize: GRID } = world;
    if (this.data !== layout) {
      R.clearStatic();
      // Own only meshes generated by this view, never shared model primitives.
      // Same-name replacements are released by geometry() before their upload.
      const scenery = layout.scenery ? TerrainScenery[layout.scenery]() : [];
      const nextMeshes = new Set([...(layout.scenery ? [] : ['terrain']), ...layout.geometries.map(descriptor => descriptor.mesh),
        ...scenery.map(mesh=>mesh.name)]);
      for (const name of this.worldMeshes) if (!nextMeshes.has(name)) R.releaseGeometry(name);
      this.worldMeshes = nextMeshes;
      R.setBattlefieldProfile(world.definition.render, world.seed);
      R.extent = EXTENT;
      R.decorSeed = world.seed >>> 0;
      R.surface = world.surface;
      // An authoritative recipe can supply its own ground skin, including material
      // weights and decorative river beds underneath the one walkable bridge surface.
      if (!layout.scenery && !layout.geometries.some(descriptor => descriptor.mesh === 'terrain')) {
      const data: number[] = [];
      let i = 0;
      if (world.surface) {
        const surface = world.surface, step = surface.step;
        for (let z = 0; z < surface.size-1; z++) for (let x = 0; x < surface.size-1; x++) {
          const wx = x*step-EXTENT, wz = z*step-EXTENT,
            at = (dx: number,dz: number) => [wx+dx, surface.heightAt(wx+dx,wz+dz)-.13, wz+dz],
            color = layout.groundColors[world.idx(wx+step*.5,wz+step*.5)*2];
          geom.tri(data,at(0,0),at(0,step),at(step,step),color);
          geom.tri(data,at(0,0),at(step,step),at(step,0),color);
        }
        // Close raised deck edges against the low exterior apron, without a second floor.
        const corners = [[-EXTENT,-EXTENT],[EXTENT,-EXTENT],[EXTENT,EXTENT],[-EXTENT,EXTENT]];
        for (let side = 0; side < 4; side++) for (let j = 0; j < surface.size-1; j++) {
          const from = corners[side], to = corners[(side+1)%4],
            point = (t: number) => [from[0]+(to[0]-from[0])*t,from[1]+(to[1]-from[1])*t],
            p = point(j/(surface.size-1)), q = point((j+1)/(surface.size-1)),
            a = [p[0],surface.heightAt(p[0],p[1])-.13,p[1]], b = [q[0],surface.heightAt(q[0],q[1])-.13,q[1]],
            lowA = [p[0],-.13,p[1]], lowB = [q[0],-.13,q[1]];
          if (b[1] > -.13) geom.tri(data,a,b,lowB,[.5,.58,.64]);
          if (a[1] > -.13) geom.tri(data,a,lowB,lowA,[.5,.58,.64]);
        }
      } else for (let z = 0; z < GRID; z++)
        for (let x = 0; x < GRID; x++) {
          const wx = x * CELL - EXTENT, wz = z * CELL - EXTENT;
          geom.tri(data, [wx, -0.13, wz], [wx, -0.13, wz + CELL],
            [wx + CELL, -0.13, wz + CELL], layout.groundColors[i++], [0, 1, 0]);
          geom.tri(data, [wx, -0.13, wz], [wx + CELL, -0.13, wz + CELL],
            [wx + CELL, -0.13, wz], layout.groundColors[i++], [0, 1, 0]);
        }
      R.geometry('terrain', data);
      }
      for (const mesh of scenery) {
        R.geometry(mesh.name,mesh.data);
        if (mesh.static) R.add(mesh.name,0,0,0,1,1,1,0xffffff,0,0,0,mesh.glow,1,'static',mesh.material);
      }
      for (const descriptor of layout.geometries) {
        const geometry = TerrainModels.geometry(descriptor);
        if (descriptor.grounded && world.surface) {
          // Painted deck furniture is baked once; terrain remains CPU authoritative.
          for (let i = 0; i < geometry.length; i += 9)
            geometry[i+1] += world.surface.heightAt(geometry[i],geometry[i+2]);
        }
        R.geometry(descriptor.mesh, geometry);
      }
      for (const p of layout.placements) {
        const args: Parameters<MeridianRenderer['add']> = [p.mesh, ...p.position, ...p.scale, p.color, ...p.rotation,
          p.glow, p.alpha, p.layer];
        if (p.material !== undefined) args.push(p.material === 'ALIEN_LIGHT' ? ALIEN_LIGHT_MATERIAL : MAT[p.material]);
        R.add(...args);
      }
      this.data = layout;
    }
    if (this.world !== world || this.fogVersion !== world.fogVersion || (fogOn && !R.fogOn)) {
      if (world.fogVersion > 0 || fogOn) R.fog(world.fogPixels, GRID);
      this.world = world;
      this.fogVersion = world.fogVersion;
    }
    R.fogOn = fogOn;
  }
}

// Placement ghosts are visual objects, never spawned simulation entities.
function createBuildingPreview(type: BuildingType, p: Position, faction: FactionId, team: PlayerTeam = 0): RenderEntity {
  return { id: 0, kind: 'building', type, x: p.x, z: p.z, rot: 0, faction, team,
    hp: 1, maxHp: 1, progress: 1, size: BUILDINGS[type].size, queue: [] };
}

    // Cosmetic building yaw only; placement, collision radii and save data stay unchanged.
    function renderEntity(R: MeridianRenderer, e: RenderEntity, time: number, options: RenderEntityOptions = {}) {
      if (e.hp <= 0) return;
      const f = FACTIONS[e.faction || FACTION_ID.FIRST],
        enemy = e.team !== -1 && e.team !== (options.localTeam ?? 0);
      let team = enemy ? 0xe98680 : f.color,
        accent = enemy ? 0xffaf87 : f.accent;
      let metal: number = f.metal,
        dark: number = f.dark;
      // Building orientation belongs to the world, not the observing party.
      const rot = e.kind === 'building' ? (e.team === 1 ? Math.PI : 0) + BUILDING_YAW : e.rot || 0,
        cs = Math.cos(rot),
        sn = Math.sin(rot);
      const ground = R.surface?.entityHeight(e) ?? 0;
      let y = ground + (
        isFlyingUnitType(e.type)
          ? 3.8 - (e.exit ? 3 * clamp(distance(e, e.exit) / e.exit.length, 0, 1) : 0) +
            Math.sin(time * 2 + e.id) * 0.22
          : e.faction === FACTION_ID.THIRD && e.kind === 'unit'
            ? 0.3 + Math.sin(time * 2 + e.id) * 0.08
            : 0);
      let layer = options.layer || 'dynamic',
        alpha = options.alpha === undefined ? 1 : options.alpha;
      let build = e.kind === 'building' ? Math.max(0.15, e.progress === undefined ? 1 : e.progress) : 1;
      if (options.tint) {
        metal = team = options.tint;
        dark = options.tint;
      }
      let ghost = options.ghost;
      if (ghost) {
        metal = 0x68717d;
        dark = 0x3b424c;
      }
      let surfaceMat =
        options.material !== undefined
          ? options.material
          : e.kind === 'building' || e.kind === 'unit'
            ? e.faction === FACTION_ID.SECOND
              ? MAT.BIO
              : MAT.METAL
            : MAT.AUTO;
      // Only model lamps/cores breathe; keep low glow below the shader's texture cutoff.
      // Tactical rings and previews stay unchanged.
      const animated = (e.kind === 'unit' || e.kind === 'building') && R.quality > 0 && !R.cinema && !ghost && !options.tint && alpha === 1 && layer === 'dynamic';
      const phase = time * (e.faction === FACTION_ID.SECOND ? 1.8 : 1.1) + e.id * 2.39996;
      const p: ModelPart = (
        shape,
        lx,
        ly,
        lz,
        sx,
        sy,
        sz,
        c,
        ry = 0,
        rx = 0,
        rz = 0,
        glow = 0,
        a = alpha,
        m = surfaceMat
      ) => {
        // Glowing Court prisms use the existing crystal shader instead of flat painted metal.
        // Explicit preview/material overrides retain authority over this model-level default.
        const resolvedMaterial = options.material === undefined && m === surfaceMat &&
          e.faction === FACTION_ID.THIRD && e.kind === 'building' && shape === 'octa' && glow >= .3
            ? MAT.CRYSTAL
            : m;
        R.add(
          shape,
          e.x + lx * cs + lz * sn,
          y + ly * build,
          e.z - lx * sn + lz * cs,
          sx,
          sy * build,
          sz,
          c,
          rot + ry,
          rx,
          rz,
          animated && glow >= .3 ? glow * (1 + (e.faction === FACTION_ID.SECOND ? .22 : .12) *
            Math.sin(phase + (e.faction === FACTION_ID.THIRD ? ly * 3 - lz * 2 : lx * .7))) : glow,
          a,
          layer,
          resolvedMaterial === PORTAL_MATERIAL && !animated ? PORTAL_STILL_MATERIAL : resolvedMaterial
        );
      };
      const ring: ModelRing = (radius, h, color = team, a = 0.7, rx = 0, ry = 0, glow = 1.2) =>
        R.add('ring', e.x, y + h, e.z, radius, 1, radius, color, ry, rx, 0, glow, a, 'effects');
      if (e.kind === 'resource') {
        if (e.type === 'crystal') {
          // Cosmetic RNG only: stable per deposit, independent of time, saves and mining RNG.
          const rand = seeded(Math.imul(e.id || 0, 0x45d9f3b) ^ 0x61c88647),
            scale = 0.55 + 0.45 * Math.min(1, Math.max(0, e.amount ?? 1800) / 1800);
          const phase = rand() * Math.PI * 2,
            count = 9 + Math.floor(rand() * 4),
            colors = [0xe7b969, 0xdba14c, 0xf0ca80, 0xc89149];
          p('rockShelf', 0, -0.06, 0, 1.72, 0.65, 1.48, 0x65605a, phase, 0, 0, 0, alpha, MAT.ROCK);
          for (let i = 0; i < count; i++) {
            let a = phase + i * 2.39996 + (rand() - 0.5) * 0.35,
              r = i < 3 ? 0.2 + rand() * 0.28 : 0.7 + rand() * 0.35;
            let h =
                (i === 0 ? 2.8 + rand() * 0.4 : i < 3 ? 1.8 + rand() * 0.7 : 0.65 + rand() * 0.95) *
                scale,
              w = (i < 3 ? 0.34 + rand() * 0.12 : 0.15 + rand() * 0.16) * (0.75 + 0.25 * scale);
            let lean = i < 3 ? 0.04 + rand() * 0.09 : 0.12 + rand() * 0.23,
              c = colors[Math.floor(rand() * colors.length)];
            p(
              'alloyShard',
              Math.sin(a) * r,
              0.12,
              Math.cos(a) * r,
              w,
              h,
              w * (i % 3 === 0 ? 0.58 : 0.82),
              c,
              a,
              lean * Math.cos(a),
              -lean * Math.sin(a),
              // Alloy remains a strong emissive source under every map profile; higher qualities add bloom.
              1.8 + rand() * 0.3,
              alpha,
              MAT.CRYSTAL
            );
          }
          for (let i = 0; i < 3; i++) {
            let a = phase + i * 2.1,
              r = 1.12 + rand() * 0.2,
              w = 0.13 + rand() * 0.08;
            p(
              'alloyShard',
              Math.sin(a) * r,
              0.04,
              Math.cos(a) * r,
              w,
              (0.18 + rand() * 0.23) * scale,
              w * 0.65,
              colors[i],
              a,
              0.45,
              0.25,
              1.4,
              alpha,
              MAT.CRYSTAL
            );
          }
          // A procedural pool conveys the deposit's warm light on the surrounding terrain.
          R.add('plane', e.x, ground + 0.025, e.z, 7, 1, 7, 0xffb84f, 0, 0, 0, 0, alpha,
            'effects', ALLOY_LIGHT_MATERIAL);
        } else {
          p('aetherVent', 0, 0, 0, 1, 1, 1, 0xffffff, 0, 0, 0, 0, alpha, MAT.METAL);
          p('ring', 0, 0.465, 0, 1.69, 1, 1.521, 0x65e5e9, 0, 0, 0, 0.85, alpha, MAT.CRYSTAL);
          p('ring', 0, 0.985, 0, 0.36, 1, 0.324, 0x65e5e9, 0, 0, 0, 0.65, alpha, MAT.CRYSTAL);
          p('octa', 0, 1.64, 0, 0.43, 0.62, 0.43, 0x50dce6, time * 0.15, 0, 0, 0.45, alpha, MAT.CRYSTAL);
          for (let i = 0; i < 3; i++) {
            let t = (time * 0.35 + i * 0.33) % 1;
            R.add(
              'sphere',
              e.x + Math.sin(time + i) * 0.3,
              ground + 0.6 + t * 3,
              e.z,
              0.35 + t * 0.8,
              0.4 + t * 0.6,
              0.35 + t * 0.8,
              0x88ddd3,
              0,
              0,
              0,
              0.5,
              (1 - t) * 0.12,
              'effects'
            );
          }
        }
        return;
      }
      // Two triangles per visible entity, batched with effects; never a shadow caster.
      // Exclude menus, placement previews and Performance. No RNG, textures or model changes.
      if (R.quality > 0 && !R.cinema && !ghost && !options.tint && alpha === 1 && layer === 'dynamic') {
        const width = (e.size || 1) * (e.kind === 'building' ? 3.2 : 3.6);
        R.add('plane', e.x, (R.surface?.heightAt(e.x,e.z) ?? 0) - .02, e.z, width, 1, width * (e.kind === 'building' ? 1 : .8),
          0xffffff, rot, 0, 0, 0, e.kind === 'building' ? .32 : isFlyingUnitType(e.type) ? .12 : .26,
          'effects', CONTACT_SHADOW_MATERIAL);
      }
      if (e.kind === 'building') {
        let s = e.size || 3;
        if (e.faction === FACTION_ID.SECOND) {
          // The queen sits in her model-owned five-petal flower, with no soil plinth.
          // Other Choir buildings retain the shared mound, including in build previews.
          if (e.type !== 'hq') p('choirMound', 0, 0, 0, s, 1, s, ghost ? 0x68717d : options.tint || 0x70523b,
            0, 0, 0, 0, alpha, options.material ?? MAT.ROCK);
        } else if (!(e.faction === FACTION_ID.THIRD && ['barracks','depot','factory','hangar','hq','turret'].includes(e.type))) {
          // Court structures with bespoke silhouettes own angular foundations, without a circular dais.
          p('hex', 0, 0.15, 0, s * 1.09, 0.3, s * 1.09, 0x384552, 0.12);
          p('ring', 0, 0.33, 0, s * 1.03, 0.1, s * 1.03, team, 0, 0, 0, 0.4);
        }
        const model = EntityModels.find(e);
        if (model) {
          model.render({ entity: e, time, part: p, ring, metal, dark, team, accent, baseRotation: rot,
            surfaceColor: color => ghost ? 0x68717d : options.tint || color });
        }
        if (build < 1) {
          for (let i = 0; i < 4; i++) {
            let a = (i * Math.PI) / 2 + 0.78;
            R.add(
              'box',
              e.x + Math.sin(a) * s,
              ground + 2,
              e.z + Math.cos(a) * s,
              0.1,
              4,
              0.1,
              team,
              0,
              0,
              0,
              0.4,
              0.65,
              'effects'
            );
          }
          ring(s * 1.25, 0.13, team, 0.7);
        }
        return;
      }
      const model = EntityModels.find(e);
      if (model) {
        model.render({ entity: e, time, part: p, ring, metal, dark, team, accent, baseRotation: rot,
          surfaceColor: color => ghost ? 0x68717d : options.tint || color });
        return;
      }
    }
